# Stage 2: Serve the React application using Nginx
FROM nginx:alpine

# Remove the default Nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Install gettext for envsubst (environment variable substitution)
RUN apk add --no-cache gettext

# Copy the built files from the build stage
COPY --from=build /app/build /usr/share/nginx/html

# Copy the custom NGINX configuration template file
COPY nginx.conf.template /etc/nginx/templates/nginx.conf.template

# Expose port 80
EXPOSE 80

# Start Nginx server with environment variable substitution using ash
ENTRYPOINT ["/bin/ash", "-c", "envsubst '\$SERVER_NAME \$RESOLVER_IP \$REACT_APP_BACKEND_SERVICE' < /etc/nginx/templates/nginx.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]
